on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
        description: Working directory to find the rust crate
      branch:
        type: string
        default: "main"
        description: Branch where to look for the dep
      dry_run:
        type: string
        default: "false"
        description: "Should the update be done or just a dry run"

jobs:
  test:
    name: Check for Rust Auto-Discovery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github wide resources
        uses: actions/checkout@v3
        with:
          ref: 'v1.1.0'
          repository: ForesightMiningSoftwareCorporation/github
          path: '.github_wide_resources'
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
      - uses: tibdex/github-app-token@v1.8
        id: generate_token
        with:
          app_id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private_key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
      - name: Run UpdateCli Autodiscovery
        shell: bash
        run: |
          updatecli ${{ inputs.dry_run == 'true' && 'diff' || 'apply' }} --experimental --config $GITHUB_WORKSPACE/.github_wide_resources/updatecli/updatecli.d/rust/autodiscovery.yml --values $GITHUB_WORKSPACE/.github_wide_resources/updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ vars.UPDATECLI_BOT_GITHUB_ACTOR }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          UPDATECLI_BRANCH: ${{ inputs.branch }}
          UPDATECLI_REPO: ${{ github.event.repository.name }}
          UPDATECLI_ROOTDIR: ${{ inputs.working-directory }}
          UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_URL: ${{ secrets.CARGO_PRIVATE_REGISTRY_GIT_HTTP_URL }}
          UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_USERNAME: ${{ secrets.CARGO_PRIVATE_REGISTRY_GIT_HTTP_USERNAME }}
          UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_PASSWORD: ${{ secrets.CARGO_PRIVATE_REGISTRY_GIT_HTTP_PASSWORD }}